// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: portnums.proto

package meshtastic_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
// For any new 'apps' that run on the device or via sister apps on phones/PCs they should pick and use a
// unique 'portnum' for their application.
//
// If you are making a new app using meshtastic, please send in a pull request to add your 'portnum' to this
// master table.  PortNums should be assigned in the following range:
//
// 0-63   Core Meshtastic use, do not use for third party apps
// 64-127 Registered 3rd party apps, send in a pull request that adds a new entry to portnums.proto to  register your application
// 256-511 Use one of these portnums for your private applications that you don't want to register publically
//
// All other values are reserved.
//
// Note: This was formerly a Type enum named 'typ' with the same id #
//
// We have change to this 'portnum' based scheme for specifying app handlers for particular payloads.
// This change is backwards compatible by treating the legacy OPAQUE/CLEAR_TEXT values identically.
type PortNum int32

const (
	//
	// Deprecated: do not use in new code (formerly called OPAQUE)
	// A message sent from a device outside of the mesh, in a form the mesh does not understand
	// NOTE: This must be 0, because it is documented in IMeshService.aidl to be so
	PortNum_UNKNOWN_APP PortNum = 0
	//
	// A simple UTF-8 text message, which even the little micros in the mesh
	// can understand and show on their screen eventually in some circumstances
	// even signal might send messages in this form (see below)
	// Formerly called CLEAR_TEXT
	PortNum_TEXT_MESSAGE_APP PortNum = 1
	//
	// A message receive acknowledgment, sent in cleartext - allows radio to
	// show user that a message has been read by the recipient, optional
	//
	// Note: this concept has been removed for now.  Once READACK is implemented, use the
	// new packet type/port number stuff?
	//
	// @exclude
	//
	// CLEAR_READACK = 2;
	//
	// Reserved for built-in GPIO/example app.
	// See remote_hardware.proto/HardwareMessage for details on the message sent/received to this port number
	PortNum_REMOTE_HARDWARE_APP PortNum = 2
	//
	// The built-in position messaging app.
	// See Position for details on the message sent to this port number.
	PortNum_POSITION_APP PortNum = 3
	//
	// The built-in user info app.
	// See User for details on the message sent to this port number.
	PortNum_NODEINFO_APP PortNum = 4
	//
	// Provides a 'ping' service that replies to any packet it receives.
	// Also this serves as a small example plugin.
	PortNum_REPLY_APP PortNum = 32
	//
	// Used for the python IP tunnel feature
	PortNum_IP_TUNNEL_APP PortNum = 33
	//
	// Provides a format to send and receive environmental data from the Meshtastic network.
	//
	// Maintained by Charles Crossan (crossan007) : crossan007@gmail.com
	PortNum_ENVIRONMENTAL_MEASUREMENT_APP PortNum = 34
	//* Provides a hardware serial interface to send and receive from the Meshtastic network.
	//Connect to the RX/TX pins of a device with 38400 8N1. Packets received from the Meshtastic
	//network is forwarded to the RX pin while sending a packet to TX will go out to the Mesh
	//network. Maximum packet size of 240 bytes.
	//
	//Plugin is disabled by default can be turned on by setting SERIALPLUGIN_ENABLED = 1 in
	//SerialPlugh.cpp.
	//
	//Maintained by Jm Casler (MC Hamster) : jm@casler.org
	//
	PortNum_SERIAL_APP PortNum = 64
	//
	// STORE_FORWARD_APP (Work in Progress)
	//
	// Maintained by Jm Casler (MC Hamster) : jm@casler.org
	PortNum_STORE_FORWARD_APP PortNum = 65
	//
	// STORE_FORWARD_APP (Work in Progress)
	//
	// Maintained by Jm Casler (MC Hamster) : jm@casler.org
	PortNum_RANGE_TEST_APP PortNum = 66
	//
	// Private applications should use portnums >= 256.
	// To simplify initial development and testing you can use "PRIVATE_APP"
	// in your code without needing to rebuild protobuf files (via bin/regin_protos.sh)
	PortNum_PRIVATE_APP PortNum = 256
	//
	// ATAK Forwarder Plugin https://github.com/paulmandal/atak-forwarder
	PortNum_ATAK_FORWARDER PortNum = 257
)

// Enum value maps for PortNum.
var (
	PortNum_name = map[int32]string{
		0:   "UNKNOWN_APP",
		1:   "TEXT_MESSAGE_APP",
		2:   "REMOTE_HARDWARE_APP",
		3:   "POSITION_APP",
		4:   "NODEINFO_APP",
		32:  "REPLY_APP",
		33:  "IP_TUNNEL_APP",
		34:  "ENVIRONMENTAL_MEASUREMENT_APP",
		64:  "SERIAL_APP",
		65:  "STORE_FORWARD_APP",
		66:  "RANGE_TEST_APP",
		256: "PRIVATE_APP",
		257: "ATAK_FORWARDER",
	}
	PortNum_value = map[string]int32{
		"UNKNOWN_APP":                   0,
		"TEXT_MESSAGE_APP":              1,
		"REMOTE_HARDWARE_APP":           2,
		"POSITION_APP":                  3,
		"NODEINFO_APP":                  4,
		"REPLY_APP":                     32,
		"IP_TUNNEL_APP":                 33,
		"ENVIRONMENTAL_MEASUREMENT_APP": 34,
		"SERIAL_APP":                    64,
		"STORE_FORWARD_APP":             65,
		"RANGE_TEST_APP":                66,
		"PRIVATE_APP":                   256,
		"ATAK_FORWARDER":                257,
	}
)

func (x PortNum) Enum() *PortNum {
	p := new(PortNum)
	*p = x
	return p
}

func (x PortNum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortNum) Descriptor() protoreflect.EnumDescriptor {
	return file_portnums_proto_enumTypes[0].Descriptor()
}

func (PortNum) Type() protoreflect.EnumType {
	return &file_portnums_proto_enumTypes[0]
}

func (x PortNum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortNum.Descriptor instead.
func (PortNum) EnumDescriptor() ([]byte, []int) {
	return file_portnums_proto_rawDescGZIP(), []int{0}
}

var File_portnums_proto protoreflect.FileDescriptor

var file_portnums_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x72, 0x74, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2a, 0x94, 0x02, 0x0a, 0x07, 0x50, 0x6f, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x0f, 0x0a, 0x0b,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x00, 0x12, 0x14, 0x0a,
	0x10, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x41, 0x50,
	0x50, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x5f, 0x48, 0x41,
	0x52, 0x44, 0x57, 0x41, 0x52, 0x45, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c,
	0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x03, 0x12, 0x10,
	0x0a, 0x0c, 0x4e, 0x4f, 0x44, 0x45, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x04,
	0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x50, 0x4c, 0x59, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x20, 0x12,
	0x11, 0x0a, 0x0d, 0x49, 0x50, 0x5f, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x41, 0x50, 0x50,
	0x10, 0x21, 0x12, 0x21, 0x0a, 0x1d, 0x45, 0x4e, 0x56, 0x49, 0x52, 0x4f, 0x4e, 0x4d, 0x45, 0x4e,
	0x54, 0x41, 0x4c, 0x5f, 0x4d, 0x45, 0x41, 0x53, 0x55, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x41, 0x50, 0x50, 0x10, 0x22, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x52, 0x49, 0x41, 0x4c, 0x5f,
	0x41, 0x50, 0x50, 0x10, 0x40, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x5f, 0x46,
	0x4f, 0x52, 0x57, 0x41, 0x52, 0x44, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x41, 0x12, 0x12, 0x0a, 0x0e,
	0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x42,
	0x12, 0x10, 0x0a, 0x0b, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x50, 0x50, 0x10,
	0x80, 0x02, 0x12, 0x13, 0x0a, 0x0e, 0x41, 0x54, 0x41, 0x4b, 0x5f, 0x46, 0x4f, 0x52, 0x57, 0x41,
	0x52, 0x44, 0x45, 0x52, 0x10, 0x81, 0x02, 0x42, 0x43, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x65, 0x65, 0x6b, 0x73, 0x76, 0x69, 0x6c, 0x6c, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x42, 0x08,
	0x50, 0x6f, 0x72, 0x74, 0x6e, 0x75, 0x6d, 0x73, 0x48, 0x03, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x37, 0x2f, 0x6d,
	0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2d, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_portnums_proto_rawDescOnce sync.Once
	file_portnums_proto_rawDescData = file_portnums_proto_rawDesc
)

func file_portnums_proto_rawDescGZIP() []byte {
	file_portnums_proto_rawDescOnce.Do(func() {
		file_portnums_proto_rawDescData = protoimpl.X.CompressGZIP(file_portnums_proto_rawDescData)
	})
	return file_portnums_proto_rawDescData
}

var file_portnums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_portnums_proto_goTypes = []interface{}{
	(PortNum)(0), // 0: PortNum
}
var file_portnums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_portnums_proto_init() }
func file_portnums_proto_init() {
	if File_portnums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_portnums_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_portnums_proto_goTypes,
		DependencyIndexes: file_portnums_proto_depIdxs,
		EnumInfos:         file_portnums_proto_enumTypes,
	}.Build()
	File_portnums_proto = out.File
	file_portnums_proto_rawDesc = nil
	file_portnums_proto_goTypes = nil
	file_portnums_proto_depIdxs = nil
}
